[package]
name = "mithra"
version = "0.1.0"
license = "MIT OR APACHE-2.0"
edition = "2021"

[lib]
name = "mithra_lib"
path = "src/lib.rs"

[[bin]]
name = "mithra"
path = "src/main.rs"
required-features = ["bin-dependencies"]

[features]
default = ["bin-dependencies"]
bin-dependencies = ["flexi_logger", "clap"]

[dependencies]
clap = { version = "4", features = ["derive"], optional = true }
flexi_logger = { version = "0.27", optional = true }
log = "0.4"
anyhow = { version = "1" }
spdx = { version = "0.10", features = ["text"] }
spdx-rs = "0.5"
serde_json = "1"
termtree = "0.4"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
regex = "1"
once_cell = "1"
